## Name: Shreyash Shinkar
## Roll no: 31373
## DSBDAL Assignment 6 - Data Analytics III

### Continuing from Data Visualization III.....

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
iris = pd.read_csv("Iris.csv")

In [3]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [6]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
print(iris["Species"].unique())
print(iris["Species"].value_counts())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64


### As observed above, we have 4 feature variables - SepalLengthCm, SepalWidthCm, PetalLengthCm and PetalWidthCm, all of which are numerical. The target variable Species is a categorical/nominal variable with 3 different unique types - Iris-setosa, Iris-versicolor and Iris-virginica. The target variables are equal in count with each variable appearing exactly 50 times.

In [9]:
iris.corr()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.716676     -0.397729       0.882747   
SepalLengthCm  0.716676       1.000000     -0.109369       0.871754   
SepalWidthCm  -0.397729      -0.109369      1.000000      -0.420516   
PetalLengthCm  0.882747       0.871754     -0.420516       1.000000   
PetalWidthCm   0.899759       0.817954     -0.356544       0.962757   

               PetalWidthCm  
Id                 0.899759  
SepalLengthCm      0.817954  
SepalWidthCm      -0.356544  
PetalLengthCm      0.962757  
PetalWidthCm       1.000000

In [11]:
features = iris.iloc[:, 1:5]

In [12]:
features.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [14]:
target = iris.iloc[:, -1]

In [15]:
target.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [17]:
print('The Initial DataFrame Contained %d Rows And %d Columns'%(iris.shape))

print('The Features Matrix Contains %d Rows And %d Columns'%(features.shape))

print('The Target Vector Contains %d Rows And %d Columns'%(np.array(target).reshape(-1, 1).shape))

The Initial DataFrame Contained 150 Rows And 6 Columns
The Features Matrix Contains 150 Rows And 4 Columns
The Target Vector Contains 150 Rows And 1 Columns


In [18]:
from sklearn.naive_bayes import GaussianNB
algorithm = GaussianNB(priors=None, var_smoothing=1e-9)

In [19]:
algorithm.fit(features, target)

GaussianNB(priors=None, var_smoothing=1e-09)

In [20]:
print(algorithm.classes_)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [21]:
print('The Gaussian Model Has Achieved %.2f Percent Accuracy'%(algorithm.score(features, target)))

The Gaussian Model Has Achieved 0.96 Percent Accuracy


In [24]:
observation = [[5.0, 3.7, 1.6, 0.1]]
predictions=algorithm.predict(observation)
print(predictions)

['Iris-setosa']


In [25]:
from sklearn.model_selection import train_test_split

In [27]:
x=iris[['SepalLengthCm','PetalLengthCm','PetalWidthCm','SepalWidthCm']]
y=iris['Species']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [28]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)

In [29]:
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica'],
      dtype='<U15')

In [30]:
x_test

SepalLengthCm  PetalLengthCm  PetalWidthCm  SepalWidthCm
71             6.1            4.0           1.3           2.8
124            6.7            5.7           2.1           3.3
28             5.2            1.4           0.2           3.4
143            6.8            5.9           2.3           3.2
117            7.7            6.7           2.2           3.8
48             5.3            1.5           0.2           3.7
81             5.5            3.7           1.0           2.4
32             5.2            1.5           0.1           4.1
41             4.5            1.3           0.3           2.3
50             7.0            4.7           1.4           3.2
85             6.0            4.5           1.6           3.4
63             6.1            4.7           1.4           2.9
110            6.5            5.1           2.0           3.2
125            7.2            6.0           1.8           3.2
76             6.8            4.8           1.4           2.8
27             5.2            1.5           0.2           3.5
139            6.9            5.4           2.1           3.1
47             4.6            1.4           0.2           3.2
34             4.9            1.5           0.1           3.1
111            6.4            5.3           1.9           2.7
46             5.1            1.6           0.2           3.8
60             5.0            3.5           1.0           2.0
87             6.3            4.4           1.3           2.3
17             5.1            1.4           0.3           3.5
136            6.3            5.6           2.4           3.4
78             6.0            4.5           1.5           2.9
69             5.6            3.9           1.1           2.5
99             5.7            4.1           1.3           2.8
73             6.1            4.7           1.2           2.8
133            6.3            5.1           1.5           2.8

In [31]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8666666666666667


In [32]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[9 0 0]
 [0 8 4]
 [0 0 9]]
